"""add_product_prices_inventory

Revision ID: 3b11e4c15fb8
Revises: 6fe7c2197b3c
Create Date: 2026-06-24 21:32:57.690723
"""
from alembic import op
import sqlalchemy as sa


revision = '3b11e4c15fb8'
down_revision = '6fe7c2197b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_inventory',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse', sa.String(length=50), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), nullable=False),
    sa.Column('qty_reserved', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse', name='uq_product_warehouse')
    )
    op.create_index(op.f('ix_product_inventory_product_id'), 'product_inventory', ['product_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'channel', name='uq_product_channel')
    )
    op.create_index(op.f('ix_product_prices_channel'), 'product_prices', ['channel'], unique=False)
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.add_column('products', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('packaging_info', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('weight_g', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'weight_g')
    op.drop_column('products', 'packaging_info')
    op.drop_column('products', 'barcode')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_channel'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_product_inventory_product_id'), table_name='product_inventory')
    op.drop_table('product_inventory')
    # ### end Alembic commands ###
