"""create_dealer_tables

Revision ID: 6fe7c2197b3c
Revises: e4b618158cdb
Create Date: 2026-06-24 21:06:27.115396
"""
from alembic import op
import sqlalchemy as sa


revision = '6fe7c2197b3c'
down_revision = 'e4b618158cdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealers',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_term_days', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealers_code'), 'dealers', ['code'], unique=True)
    op.create_index(op.f('ix_dealers_region'), 'dealers', ['region'], unique=False)
    op.create_index(op.f('ix_dealers_status'), 'dealers', ['status'], unique=False)
    op.create_table('dealer_discounts',
    sa.Column('dealer_id', sa.Uuid(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_discounts_category_id'), 'dealer_discounts', ['category_id'], unique=False)
    op.create_index(op.f('ix_dealer_discounts_dealer_id'), 'dealer_discounts', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_discounts_product_id'), 'dealer_discounts', ['product_id'], unique=False)
    op.create_index(op.f('ix_dealer_discounts_tier'), 'dealer_discounts', ['tier'], unique=False)
    op.create_table('dealer_ledger',
    sa.Column('dealer_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_ledger_dealer_id'), 'dealer_ledger', ['dealer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dealer_ledger_dealer_id'), table_name='dealer_ledger')
    op.drop_table('dealer_ledger')
    op.drop_index(op.f('ix_dealer_discounts_tier'), table_name='dealer_discounts')
    op.drop_index(op.f('ix_dealer_discounts_product_id'), table_name='dealer_discounts')
    op.drop_index(op.f('ix_dealer_discounts_dealer_id'), table_name='dealer_discounts')
    op.drop_index(op.f('ix_dealer_discounts_category_id'), table_name='dealer_discounts')
    op.drop_table('dealer_discounts')
    op.drop_index(op.f('ix_dealers_status'), table_name='dealers')
    op.drop_index(op.f('ix_dealers_region'), table_name='dealers')
    op.drop_index(op.f('ix_dealers_code'), table_name='dealers')
    op.drop_table('dealers')
    # ### end Alembic commands ###
