"""add_qrcode_and_traceability

Revision ID: bd7a925aa1b3
Revises: 407d506b6033
Create Date: 2026-06-24 21:56:55.930202
"""
from alembic import op
import sqlalchemy as sa


revision = 'bd7a925aa1b3'
down_revision = '407d506b6033'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_batches',
    sa.Column('batch_no', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('manufacture_date', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('origin_region', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_batches_batch_no'), 'product_batches', ['batch_no'], unique=True)
    op.create_index(op.f('ix_product_batches_product_id'), 'product_batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_batches_status'), 'product_batches', ['status'], unique=False)
    op.create_table('qr_codes',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('single_use', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_codes_batch_id'), 'qr_codes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_qr_codes_status'), 'qr_codes', ['status'], unique=False)
    op.create_index(op.f('ix_qr_codes_token'), 'qr_codes', ['token'], unique=True)
    op.create_table('qr_scan_logs',
    sa.Column('qr_code_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['qr_code_id'], ['qr_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_scan_logs_qr_code_id'), 'qr_scan_logs', ['qr_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_scan_logs_qr_code_id'), table_name='qr_scan_logs')
    op.drop_table('qr_scan_logs')
    op.drop_index(op.f('ix_qr_codes_token'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_status'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_batch_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index(op.f('ix_product_batches_status'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_product_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_batch_no'), table_name='product_batches')
    op.drop_table('product_batches')
    # ### end Alembic commands ###
